#231 switch from xsd:double to xsd:decimal
ESIPFed/sweet pull request #269
Opened 2022-09-08 10:57 UTC by jmkeil

Solving #231 by replacing xsd:double with xsd:decimal for conversion values and beyond.

Please not, that this is a breaking change, as it might change datatypes used in tools to represent parsed values.

2022-09-08 11:20 UTC, dr-shorthair reviewed
In general I prefer `xsd:decimal` for serialization, and almost always specify `xsd:decimal` in my designs. It is more 'honest', and has arbitrary precision. 

It does get a bit unwieldy for very large and very small numbers (large positive and negative exponents in scientific notation), but that is really just in a Human-oriented UI. 

However, as you note, it is _potentially_ incompatible with some existing applications, so feedback on this should be sought before proceeding.

2023-02-15 23:05 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "100000000.0"^^xsd:decimal
should be 0.00000001

2023-02-15 23:48 UTC, brandonnodnarb requested changes
in `stateEnergyFlux.ttl` there were errors in the form of NE-n were converted to NEn.  

Example:
`"9.0E-4"^^xsd:double` was converted to `"90000.0"^^xsd:decimal` instead of `"0.0009"^^xsd:decimal`.  Added comments for each as appropriate.

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "10000000.0"^^xsd:decimal
should be 0.0000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "10000000.0"^^xsd:decimal
should be 0.0000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "1000000.0"^^xsd:decimal
should be 0.000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "1000000.0"^^xsd:decimal
should be 0.000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "100000.0"^^xsd:decimal
should be 0.00001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "100000.0"^^xsd:decimal
should be 0.00001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "10000.0"^^xsd:decimal
should be 0.0001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                             owl:hasValue "10000.0"^^xsd:decimal
should be 0.0001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "100000000.0"^^xsd:decimal ;
should be 0.00000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "200000000.0"^^xsd:decimal
should be 0.00000002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "200000000.0"^^xsd:decimal ;
should be 0.00000002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "300000000.0"^^xsd:decimal
should be 0.00000003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "300000000.0"^^xsd:decimal ;
0.00000003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "400000000.0"^^xsd:decimal
0.00000004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "400000000.0"^^xsd:decimal ;
0.00000004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "500000000.0"^^xsd:decimal
0.00000005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "500000000.0"^^xsd:decimal ;
0.00000005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "600000000.0"^^xsd:decimal
0.00000006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "600000000.0"^^xsd:decimal ;
0.00000006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "700000000.0"^^xsd:decimal
0.00000007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "700000000.0"^^xsd:decimal ;
0.00000007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "800000000.0"^^xsd:decimal
0.00000008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "800000000.0"^^xsd:decimal ;
0.00000008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "900000000.0"^^xsd:decimal
0.00000009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "900000000.0"^^xsd:decimal ;
0.00000009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "10000000.0"^^xsd:decimal
0.0000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "10000000.0"^^xsd:decimal ;
0.0000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "20000000.0"^^xsd:decimal
0.0000002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "20000000.0"^^xsd:decimal ;
0.0000002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "30000000.0"^^xsd:decimal
0.0000003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "30000000.0"^^xsd:decimal ;
0.0000003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "40000000.0"^^xsd:decimal
0.0000004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "40000000.0"^^xsd:decimal ;
0.0000004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "50000000.0"^^xsd:decimal
0.0000005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "50000000.0"^^xsd:decimal ;
0.0000005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "60000000.0"^^xsd:decimal
0.0000006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "60000000.0"^^xsd:decimal ;
0.0000006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "70000000.0"^^xsd:decimal
0.0000007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "70000000.0"^^xsd:decimal ;
0.0000007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "80000000.0"^^xsd:decimal
0.0000008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "80000000.0"^^xsd:decimal ;
0.0000008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "90000000.0"^^xsd:decimal
0.0000009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "90000000.0"^^xsd:decimal ;
0.0000009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "1000000.0"^^xsd:decimal
0.000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "1000000.0"^^xsd:decimal ;
0.000001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "2000000.0"^^xsd:decimal
0.000002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "2000000.0"^^xsd:decimal ;
0.000002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "3000000.0"^^xsd:decimal
0.000003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "3000000.0"^^xsd:decimal ;
0.000003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "4000000.0"^^xsd:decimal
0.000004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "4000000.0"^^xsd:decimal ;
0.000004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "5000000.0"^^xsd:decimal
0.000005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "5000000.0"^^xsd:decimal ;
0.000005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "6000000.0"^^xsd:decimal
0.000006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "6000000.0"^^xsd:decimal ;
0.000006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "7000000.0"^^xsd:decimal
0.000007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "7000000.0"^^xsd:decimal ;
0.000007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "8000000.0"^^xsd:decimal
0.000008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "8000000.0"^^xsd:decimal ;
0.000008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "9000000.0"^^xsd:decimal
0.000009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "9000000.0"^^xsd:decimal ;
0.000009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "1000000.0"^^xsd:decimal
shouldn't this be 1.0E-5? (boundary between C9 and M1)
or, 0.00001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "100000.0"^^xsd:decimal ;
0.00001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "200000.0"^^xsd:decimal
0.00002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "200000.0"^^xsd:decimal ;
0.00002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "300000.0"^^xsd:decimal
0.00003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "300000.0"^^xsd:decimal ;
0.00003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "400000.0"^^xsd:decimal
0.00004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "400000.0"^^xsd:decimal ;
0.00004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "500000.0"^^xsd:decimal
0.00005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "500000.0"^^xsd:decimal ;
0.00005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "600000.0"^^xsd:decimal
0.00006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "600000.0"^^xsd:decimal ;
0.00006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "700000.0"^^xsd:decimal
0.00007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "700000.0"^^xsd:decimal ;
0.00007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "800000.0"^^xsd:decimal
0.00008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "800000.0"^^xsd:decimal ;
0.00008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "900000.0"^^xsd:decimal
0.00009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "900000.0"^^xsd:decimal ;
0.00009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "10000.0"^^xsd:decimal
0.0001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "10000.0"^^xsd:decimal ;
0.0001

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "20000.0"^^xsd:decimal
0.0002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "20000.0"^^xsd:decimal ;
0.0002

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "30000.0"^^xsd:decimal
0.0003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "30000.0"^^xsd:decimal ;
0.0003

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "40000.0"^^xsd:decimal
0.0004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "40000.0"^^xsd:decimal ;
0.0004

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "50000.0"^^xsd:decimal
0.0005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "50000.0"^^xsd:decimal ;
0.0005

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "60000.0"^^xsd:decimal
0.0006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "60000.0"^^xsd:decimal ;
0.0006

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "70000.0"^^xsd:decimal
0.0007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "70000.0"^^xsd:decimal ;
0.0007

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "80000.0"^^xsd:decimal
0.0008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "80000.0"^^xsd:decimal ;
0.0008

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "90000.0"^^xsd:decimal
0.0009

2023-02-15 23:48 UTC, brandonnodnarb commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "90000.0"^^xsd:decimal ;
0.0009

2023-02-16 00:00 UTC, brandonnodnarb commented
> it is potentially incompatible with some existing applications, so feedback on this should be sought before proceeding.

Indeed.  I interpret this a 'more' correct.  I advocate making the change and highlighting the change it in the v3.6 release info.

I think I corrected the negative to positive exponent issues.  Can someone please verify?

2023-02-16 09:57 UTC, jmkeil reviewed
Sorry. Here something went wrong during the replacement. Looks good now.

2023-03-15 20:41 UTC, rduerr commented on src/relaMath.ttl
Looks good

2023-03-15 20:56 UTC, rduerr approved these changes
Looks good!

2023-03-15 21:13 UTC, rduerr commented
@jmkeil Can you please fix the conflicts in src/reprSciUnits.ttl.  I was concerned about changing the abbreviation for Siemens from S to G, in particular...

2023-04-11 19:50 UTC, brandonnodnarb approved these changes

2023-05-17 20:40 UTC, r0sek approved these changes

2023-05-17 20:40 UTC, r0sek commented
Approved

2023-05-17 20:46 UTC, brandonnodnarb commented
closed on accident.

2023-05-17 20:55 UTC, r0sek approved these changes

2023-05-17 20:55 UTC, brandonnodnarb approved these changes
FIxed symbol/abbreviation mismatch

2023-05-17 20:56 UTC, merged