229 fix conversion factors and offsets
ESIPFed/sweet pull request #270
Opened 2022-09-08 13:33 UTC by jmkeil

Fixes the wrong conversion factors and offsets noted in #229.

Please not that this PR is based on PR #269 to avoid later merge conflicts.

2023-02-15 21:47 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "200000000.0"^^xsd:decimal
Shouldn't this be .00000002 instead of 20000000.0?

2023-02-15 21:47 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "100000000.0"^^xsd:decimal ;
Shouldn't this be .00000001 instead of 100000000.0?

2023-02-15 21:49 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "200000000.0"^^xsd:decimal ;
Shouldn't this be .00000002?

2023-02-15 21:49 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "300000000.0"^^xsd:decimal
Shouldn't this be .00000003?

2023-02-15 22:36 UTC, rduerr requested changes
The stateEnergyFlux file has a large number of issues where numbers like 4.0e-3 got converted into something like 4000 instead of .004.  These all have comments and most have a line that could be cut and pasted to fix the problem.

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "70000000.0"^^xsd:decimal
sorelm:hasUpperBound ".0000007"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "70000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0000007"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "80000000.0"^^xsd:decimal
sorelm:hasUpperBound ".0000008"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "80000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0000008"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "90000000.0"^^xsd:decimal
sorelm:hasUpperBound ".0000009"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "90000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0000009"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "1000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000001"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "1000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000001"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "2000000.0"^^xsd:decimal
sorelm:hasUpperBound ".0000002"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "2000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000002"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "3000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000003"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "3000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000003"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "4000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000004"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "5000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000005"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "5000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000005"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "6000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000006"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "6000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000006"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "7000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000007"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "7000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000007"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "8000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000008"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "8000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000008"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "9000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000009"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "9000000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".000009"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "1000000.0"^^xsd:decimal
sorelm:hasUpperBound ".000001"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "100000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00001"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "200000.0"^^xsd:decimal
sorelm:hasUpperBound ".00002"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "200000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00002"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "300000.0"^^xsd:decimal
sorelm:hasUpperBound ".00003"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "300000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00003"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "400000.0"^^xsd:decimal
sorelm:hasUpperBound ".00004"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "400000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00004"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "500000.0"^^xsd:decimal
sorelm:hasUpperBound ".00005"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "500000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00005"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "600000.0"^^xsd:decimal
sorelm:hasUpperBound ".00006"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "700000.0"^^xsd:decimal
sorelm:hasUpperBound ".00007"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "700000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00007"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasUpperBound "800000.0"^^xsd:decimal
sorelm:hasUpperBound ".00008"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "900000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".00009"^^xsd:decimal ;

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "50000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0005"^^xsd:decimal ;
                                  sorelm:hasUpperBound ".0006"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "60000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0006"^^xsd:decimal ;
                                  sorelm:hasUpperBound ".0007"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "80000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0008"^^xsd:decimal ;
                                  sorelm:hasUpperBound ".0009"^^xsd:decimal

2023-02-15 22:36 UTC, rduerr commented on src/stateEnergyFlux.ttl
> +                                  sorelm:hasLowerBound "90000.0"^^xsd:decimal ;
sorelm:hasLowerBound ".0009"^^xsd:decimal ;

2023-02-15 22:37 UTC, rduerr requested changes
The stateEnergyFlux file has a large number of issues where numbers like 4.0e-3 got converted into something like 4000 instead of .004.  These all have comments and most have a line that could be cut and pasted to fix the problem.

2023-08-16 20:36 UTC, brandonnodnarb commented
addressed in #269

2023-08-16 20:36 UTC, closed without merging